import type { Recipe, Category } from '../types';

// Placeholder data for beautiful preview
export const MOCK_CATEGORIES: Category[] = [
  { id: '1', name: 'Cake', slug: 'cake', icon: '🍰', description: 'Classic and fluffy cakes', created_at: new Date().toISOString() },
  { id: '2', name: 'Cupcake', slug: 'cupcake', icon: '🧁', description: 'Bite-sized delights', created_at: new Date().toISOString() },
  { id: '3', name: 'Brownies', slug: 'brownies', icon: '🍫', description: 'Fudgy and rich', created_at: new Date().toISOString() },
  { id: '4', name: 'Cookies', slug: 'cookies', icon: '🍪', description: 'Crispy and chewy', created_at: new Date().toISOString() },
  { id: '5', name: 'Donut', slug: 'donut', icon: '🍩', description: 'Glazed perfection', created_at: new Date().toISOString() },
  { id: '6', name: 'Cheesecake', slug: 'cheesecake', icon: '🧀', description: 'Creamy indulgence', created_at: new Date().toISOString() },
  { id: '7', name: 'Pastry', slug: 'pastry', icon: '🥐', description: 'Flaky layers', created_at: new Date().toISOString() },
  { id: '8', name: 'Macaron', slug: 'macaron', icon: '🍭', description: 'Sweet French meringue', created_at: new Date().toISOString() },
];

export const MOCK_RECIPES: Recipe[] = [
  {
    id: 'r1',
    title: 'Strawberry Cloud Dream Cake',
    slug: 'strawberry-cloud-dream-cake',
    thumbnail_url: 'https://images.unsplash.com/photo-1565958011703-44f9829ba187?w=800&auto=format&fit=crop&q=60',
    description: 'A light, airy sponge cake layered with fresh strawberries and whipped cream.',
    author_id: 'u1',
    category_id: '1',
    ingredients: ['2 cups flour', '1.5 cups sugar', '1 cup milk', 'Fresh strawberries'],
    steps: ['Preheat oven to 350F', 'Mix dry ingredients', 'Fold in strawberries', 'Bake for 30 mins'],
    cooking_time: 45,
    difficulty: 'Medium',
    video_url: null,
    tips: 'Use cold cream for better peaks.',
    is_published: true,
    view_count: 1250,
    created_at: new Date().toISOString(),
    category: MOCK_CATEGORIES[0],
    author: {
      id: 'u1',
      username: 'baking_queen',
      full_name: 'Elena Rose',
      avatar_url: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&auto=format&fit=crop&q=60',
      role: 'admin',
      bio: 'Lover of all things sweet.',
      updated_at: new Date().toISOString()
    }
  },
  {
    id: 'r2',
    title: 'Velvet Pink Glazed Donuts',
    slug: 'velvet-pink-glazed-donuts',
    thumbnail_url: 'https://images.unsplash.com/photo-1527515545081-5db817172677?w=800&auto=format&fit=crop&q=60',
    description: 'Soft, melt-in-your-mouth donuts with a glossy beetroot-infused pink glaze.',
    author_id: 'u1',
    category_id: '5',
    ingredients: ['Yeast', 'Flour', 'Beetroot juice', 'Sugar'],
    steps: ['Proof yeast', 'Knead dough', 'Fry until golden', 'Glaze while warm'],
    cooking_time: 90,
    difficulty: 'Hard',
    video_url: null,
    tips: 'Ensure oil is exactly 375F.',
    is_published: true,
    view_count: 840,
    created_at: new Date().toISOString(),
    category: MOCK_CATEGORIES[4]
  },
  {
    id: 'r3',
    title: 'Double Choco Brownie Box',
    slug: 'double-choco-brownie-box',
    thumbnail_url: 'https://images.unsplash.com/photo-1461008108145-92427abb01c0?w=800&auto=format&fit=crop&q=60',
    description: 'Ultra fudgy brownies with chocolate chunks and a pinch of sea salt.',
    author_id: 'u2',
    category_id: '3',
    ingredients: ['Cocoa powder', 'Dark chocolate', 'Butter', 'Eggs'],
    steps: ['Melt butter and chocolate', 'Whisk eggs and sugar', 'Combine and bake'],
    cooking_time: 30,
    difficulty: 'Easy',
    video_url: null,
    tips: 'Do not overbake!',
    is_published: true,
    view_count: 2100,
    created_at: new Date().toISOString(),
    category: MOCK_CATEGORIES[2]
  },
  {
    id: 'r4',
    title: 'Korean Bento Mini Cake',
    slug: 'korean-bento-mini-cake',
    thumbnail_url: 'https://images.unsplash.com/photo-1535141192574-5d4897c12636?w=800&auto=format&fit=crop&q=60',
    description: 'Cute, pastel-colored lunchbox cakes with minimalist aesthetic designs.',
    author_id: 'u1',
    category_id: '1',
    ingredients: ['Cake flour', 'Eggs', 'Buttercream', 'Food coloring'],
    steps: ['Bake small layers', 'Interlayer with cream', 'Frost smoothly', 'Add cute drawings'],
    cooking_time: 60,
    difficulty: 'Medium',
    video_url: null,
    tips: 'Use a small palette knife for frosting.',
    is_published: true,
    view_count: 3500,
    created_at: new Date().toISOString(),
    category: MOCK_CATEGORIES[0]
  },
  {
    id: 'r5',
    title: 'Lavender Macaron Towers',
    slug: 'lavender-macaron-towers',
    thumbnail_url: 'https://images.unsplash.com/photo-1558961363-fa8fdf82db35?w=800&auto=format&fit=crop&q=60',
    description: 'Delicate lavender-scented shells with a honey-lemon ganache filling.',
    author_id: 'u3',
    category_id: '8',
    ingredients: ['Almond flour', 'Powdered sugar', 'Lavender buds', 'Honey'],
    steps: ['Sift dry ingredients', 'Make meringue', 'Macaronage technique', 'Pipe and bake'],
    cooking_time: 120,
    difficulty: 'Hard',
    view_count: 1540,
    is_published: true,
    video_url: null,
    tips: 'Aging the shells in the fridge for 24h improves texture.',
    created_at: new Date().toISOString(),
    category: MOCK_CATEGORIES[7]
  },
  {
    id: 'r6',
    title: 'Matcha Green Tea Swirls',
    slug: 'matcha-green-tea-swirls',
    thumbnail_url: 'https://images.unsplash.com/photo-1515037893149-de7f840978e2?w=800&auto=format&fit=crop&q=60',
    description: 'Healthier muffins with high-grade matcha and white chocolate ripples.',
    author_id: 'u1',
    category_id: '2',
    ingredients: ['Matcha powder', 'White chocolate', 'Yogurt', 'Oats'],
    steps: ['Whisk wet ingredients', 'Add matcha mixture', 'Bake until fluffy'],
    cooking_time: 25,
    difficulty: 'Easy',
    view_count: 980,
    is_published: true,
    video_url: null,
    tips: 'Sift the matcha to avoid lumps.',
    created_at: new Date().toISOString(),
    category: MOCK_CATEGORIES[1]
  },
  {
    id: 'r7',
    title: 'Fluffy Cloud Cheesecake',
    slug: 'fluffy-cloud-cheesecake',
    thumbnail_url: 'https://images.unsplash.com/photo-1533134242443-d4fd215305ad?w=800&auto=format&fit=crop&q=60',
    description: 'A cheesecake so light, you might float away! ☁️',
    author_id: 'u1',
    category_id: '1',
    ingredients: ['Cream cheese', 'Eggs', 'Sugar', 'Heavy cream'],
    steps: ['Mix until airy', 'Bake with water bath', 'Chill overnight'],
    cooking_time: 240,
    difficulty: 'Medium',
    view_count: 5200,
    is_published: true,
    video_url: null,
    tips: 'Ensure all ingredients are at room temperature.',
    created_at: new Date().toISOString(),
    category: MOCK_CATEGORIES[0]
  },
  {
    id: 'r8',
    title: 'Pikachu Puddin\' Surprise',
    slug: 'pikachu-puddin-surprise',
    thumbnail_url: 'https://images.unsplash.com/photo-1551024506-0bccd828d307?w=800&auto=format&fit=crop&q=60',
    description: 'Shockingly sweet pudding with a hint of mango and chocolate ears! ⚡',
    author_id: 'u2',
    category_id: '3',
    ingredients: ['Milk', 'Custard powder', 'Mango puree', 'Chocolate chips'],
    steps: ['Heat milk', 'Stir in custard', 'Add mango', 'Decorate with ears'],
    cooking_time: 15,
    difficulty: 'Easy',
    view_count: 3100,
    is_published: true,
    video_url: null,
    tips: 'Use very ripe mangoes for the best flavor.',
    created_at: new Date().toISOString(),
    category: MOCK_CATEGORIES[2]
  },
  {
    id: 'r9',
    title: 'Bouncy Bear Brownies',
    slug: 'bouncy-bear-brownies',
    thumbnail_url: 'https://images.unsplash.com/photo-1461008108145-9a4d87da1395?w=800&auto=format&fit=crop&q=60',
    description: 'Fudgy brownies shaped like sleepy bears. Too cute to eat! 🧸',
    author_id: 'u1',
    category_id: '4',
    ingredients: ['Cocoa', 'Butter', 'Flour', 'Walnuts'],
    steps: ['Melt butter and cocoa', 'Mix ingredients', 'Pour into bear molds', 'Bake until set'],
    cooking_time: 35,
    difficulty: 'Easy',
    view_count: 4200,
    is_published: true,
    video_url: null,
    tips: 'Grease the molds thoroughly to avoid sticking.',
    created_at: new Date().toISOString(),
    category: MOCK_CATEGORIES[3]
  },
  {
    id: 'r10',
    title: 'Pink Pony Cupcakes',
    slug: 'pink-pony-cupcakes',
    thumbnail_url: 'https://images.unsplash.com/photo-1519869325930-281384150b29?w=800&auto=format&fit=crop&q=60',
    description: 'Magical vanilla cupcakes with sparkly pink frosting and sprinkles! 🦄',
    author_id: 'u3',
    category_id: '2',
    ingredients: ['Vanilla', 'Soft flour', 'Pink icing', 'Edible glitter'],
    steps: ['Bake base', 'Pipe high frosting', 'Shower with glitter'],
    cooking_time: 45,
    difficulty: 'Medium',
    view_count: 6700,
    is_published: true,
    video_url: null,
    tips: 'Wait for cupcakes to cool completely before frosting.',
    created_at: new Date().toISOString(),
    category: MOCK_CATEGORIES[1]
  },
  {
    id: 'r11',
    title: 'Giggle-Glaze Galaxy Donuts',
    slug: 'giggle-glaze-galaxy-donuts',
    thumbnail_url: 'https://images.unsplash.com/photo-1551024601-bec78aea704b?w=800&auto=format&fit=crop&q=60',
    description: 'Donuts with a glaze so shiny you can see your own laughter! 🍩✨',
    author_id: 'u1',
    category_id: '5',
    ingredients: ['Flour', 'Yeast', 'Space dust (colored sugar)', 'Milk'],
    steps: ['Fry dough circles', 'Dip in galaxy glaze', 'Watch them sparkle'],
    cooking_time: 60,
    difficulty: 'Medium',
    view_count: 8900,
    is_published: true,
    video_url: null,
    tips: 'Use a toothpick to swirl the colors for a better galaxy effect.',
    created_at: new Date().toISOString(),
    category: MOCK_CATEGORIES[4]
  },
  {
    id: 'r12',
    title: 'Sleepy Sloth Sugar Cookies',
    slug: 'sleepy-sloth-sugar-cookies',
    thumbnail_url: 'https://images.unsplash.com/photo-1499636136210-6f4ee915583e?w=800&auto=format&fit=crop&q=60',
    description: 'So soft and chewy, they take their time melting in your mouth. 🦥🍪',
    author_id: 'u2',
    category_id: '3',
    ingredients: ['Butter', 'Sugar', 'Flour', 'Patience'],
    steps: ['Cream butter and sugar', 'Add flour slowly', 'Cut into sloth shapes', 'Bake slowly'],
    cooking_time: 25,
    difficulty: 'Easy',
    view_count: 4500,
    is_published: true,
    video_url: null,
    tips: 'Chill the dough for 1 hour to prevent the sloths from spreading!',
    created_at: new Date().toISOString(),
    category: MOCK_CATEGORIES[2]
  },
  {
    id: 'r13',
    title: 'Grumpy Goblin Ginger Snaps',
    slug: 'grumpy-goblin-ginger-snaps',
    thumbnail_url: 'https://images.unsplash.com/photo-1590080875515-8a3a8dc2fe0a?w=800&auto=format&fit=crop&q=60',
    description: 'Spicy, snappy, and a little bit grumpy. Perfect for a rainy day! 👺🔥',
    author_id: 'u3',
    category_id: '3',
    ingredients: ['Ginger', 'Molasses', 'Flour', 'Cinnamon'],
    steps: ['Mix dry ingredients', 'Stir in molasses', 'Roll into balls', 'Bake until cracked'],
    cooking_time: 20,
    difficulty: 'Easy',
    view_count: 2300,
    is_published: true,
    video_url: null,
    tips: 'Roll in extra sugar before baking for maximum snap.',
    created_at: new Date().toISOString(),
    category: MOCK_CATEGORIES[2]
  },
  {
    id: 'r14',
    title: 'Wiggly Worm Watermelon Pie',
    slug: 'wiggly-worm-watermelon-pie',
    thumbnail_url: 'https://images.unsplash.com/photo-1572383664879-ac1f4a741361?w=800&auto=format&fit=crop&q=60',
    description: 'A refreshing pie that looks like a summer picnic gone wild! 🍉🐛',
    author_id: 'u1',
    category_id: '7',
    ingredients: ['Watermelon gelatin', 'Graham cracker crust', 'Gummy worms', 'Cool whip'],
    steps: ['Make watermelon filling', 'Pour into crust', 'Add gummy worms', 'Refrigerate until wiggly'],
    cooking_time: 180,
    difficulty: 'Easy',
    view_count: 3400,
    is_published: true,
    video_url: null,
    tips: 'Use fresh watermelon pieces for texture.',
    created_at: new Date().toISOString(),
    category: MOCK_CATEGORIES[6]
  },
  {
    id: 'r15',
    title: 'Panic-Free Puff Pastry',
    slug: 'panic-free-puff-pastry',
    thumbnail_url: 'https://images.unsplash.com/photo-1558961363-fa8fdf82db35?w=800&auto=format&fit=crop&q=60',
    description: 'Layers of buttery goodness without the stress! 🥐✨',
    author_id: 'u2',
    category_id: '6',
    ingredients: ['Cold butter', 'Flour', 'Ice water', 'Salt'],
    steps: ['Grate cold butter into flour', 'Fold fold fold!', 'Bake until golden and high'],
    cooking_time: 90,
    difficulty: 'Hard',
    view_count: 7600,
    is_published: true,
    video_url: null,
    tips: 'Keep everything COLD. If the butter melts, the puff is gone!',
    created_at: new Date().toISOString(),
    category: MOCK_CATEGORIES[5]
  },
  {
    id: 'r16',
    title: 'Dizzy Dragon Fruit Tarts',
    slug: 'dizzy-dragon-fruit-tarts',
    thumbnail_url: 'https://images.unsplash.com/photo-1519915028121-7d3463d20b13?w=800&auto=format&fit=crop&q=60',
    description: 'Vibrant pink tarts that will make your taste buds dance! 🐉🍓',
    author_id: 'u3',
    category_id: '8',
    ingredients: ['Tart shells', 'Dragon fruit', 'Custard', 'Mint'],
    steps: ['Fill shells with custard', 'Top with dragon fruit scoops', 'Add mint leaf'],
    cooking_time: 40,
    difficulty: 'Medium',
    view_count: 5100,
    is_published: true,
    video_url: null,
    tips: 'Use both white and red dragon fruit for a beautiful contrast.',
    created_at: new Date().toISOString(),
    category: MOCK_CATEGORIES[7]
  },
  {
    id: 'r17',
    title: 'Loopy Lemon Lava Cake',
    slug: 'loopy-lemon-lava-cake',
    thumbnail_url: 'https://images.unsplash.com/photo-1624353365286-3f8d62daad51?w=800&auto=format&fit=crop&q=60',
    description: 'A citrus explosion that flows like a yellow volcano! 🍋🌋',
    author_id: 'u1',
    category_id: '1',
    ingredients: ['Lemon curd', 'White chocolate', 'Butter', 'Flour'],
    steps: ['Melt chocolate/butter', 'Mix with eggs/flour', 'Center with lemon curd', 'Bake quickly'],
    cooking_time: 30,
    difficulty: 'Hard',
    view_count: 9200,
    is_published: true,
    video_url: null,
    tips: 'Do not overbake, or the "lava" will turn into a regular cake!',
    created_at: new Date().toISOString(),
    category: MOCK_CATEGORIES[0]
  },
  {
    id: 'r18',
    title: 'Brave Berry Brownies',
    slug: 'brave-berry-brownies',
    thumbnail_url: 'https://images.unsplash.com/photo-1624353365286-3f8d62daad51?w=800&auto=format&fit=crop&q=60',
    description: 'Double chocolate brownies stuffed with brave raspberries! 🍫🔥',
    author_id: 'u2',
    category_id: '4',
    ingredients: ['Dark chocolate', 'Raspberries', 'Eggs', 'Cocoa'],
    steps: ['Melt chocolate', 'Fold in berries carefully', 'Bake until fudgy'],
    cooking_time: 40,
    difficulty: 'Easy',
    view_count: 6300,
    is_published: true,
    video_url: null,
    tips: 'Use frozen raspberries for a cleaner look in the batter.',
    created_at: new Date().toISOString(),
    category: MOCK_CATEGORIES[3]
  }
];

export const MOCK_CHART_DATA = [
  { day: 'Mon', views: 45 },
  { day: 'Tue', views: 52 },
  { day: 'Wed', views: 38 },
  { day: 'Thu', views: 65 },
  { day: 'Fri', views: 48 },
  { day: 'Sat', views: 72 },
  { day: 'Sun', views: 85 },
];
